#!/bin/bash

# The logic to stop your application should be put in this script.
#kill `ps -ef | grep testrubyserver.rb | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
#exit 0

. "${OPENSHIFT_REPO_DIR}.openshift/config/tomcat.conf"
cd $OPENSHIFT_DATA_DIR

if [[ -d ${TOMCAT_DIR_NAME} ]]; then
	echo "Stopping tomcat server ... "
	$TOMCAT_DIR_NAME/bin/shutdown.sh
else
	echo "No tomcat proccess is running . "
fi

